from model.feature_extractor import setup_feature_extractor
from model.feature_extractor import extract_and_save_features
from model.feature_extractor import create_split_feature_files

feature_extractor_model, preprocess_fn = setup_feature_extractor()
extract_and_save_features(feature_extractor_model, preprocess_fn)
create_split_feature_files()