# Sora2 Fake Video Detection using Fully Convolutional Networks (FCN)

## Overview
This research project implements fake video detection using Vision Transformers (ViT) and Fully Convolutional Networks (FCN), building upon the work of Battocchio et al. [1].

**Methodology:**
Based on "Advance Fake Video Detection via Vision Transformers" [1], which trains a small FCN to identify AI-generated images using embeddings generated by a pretrained ViT. We extend this approach by:
- Training a similar FCN to identify frames of Sora2 videos as AI-generated
- Using a series of frame-level predictions to improve video-level performance

## References
[1] J. Battocchio, S. Dell'Anna, A. Montibeller, and G. Boato, "Advance Fake Video Detection via Vision Transformers," in Proceedings of the 2025 ACM Workshop on Information Hiding and Multimedia Security, 2025, pp. 1–11. doi: 10.1145/3733102.3733129.

## Usage

### Preprocessing & Training
**Requirements:** 
- Python 3.12.11
- GPU with CUDA support (optional, but recommended for faster processing)

**Configuration:**
- Update `device` in `config/config.yaml` to `cuda` for GPU acceleration

## Project Structure
```
fcn/
├── data/
│   ├── test/
│   │   ├── fake_videos/  (Your fake video files go here, given in config)
│   │   └── real_videos/  (Your real video files go here, given in config) 
│   ├── train/
│   │   ├── fake_videos/  (Your fake video files go here, given in config)
│   │   └── real_videos/  (Your real video files go here, given in config) 
│   └── viT_features.csv
├── config/
│   └── config.yaml
├── models/
│   ├── feature_extractor.py
│   └── fcn_classifier.py
├── utils/
│   ├── video_processing.py
│   ├── dataset.py
│   └── load_config.py
├── .gitignore
├── preprocess.py
├── Readme.md
├── train.py
└── requirements.txt
```


### Step 1: python version installation
```bash
# Install Python 3.12.11 using conda
conda install python=3.12.11

### Step 2: Environment Setup
# Install required packages
pip install -r requirements.txt
```

### Step 3: Preprocessing
```bash
python3 preprocess.py
```
This command converts videos to frames (as specified in config), extracts features using ViT, and saves them to a CSV file.
